In [2]:
import numpy as py

In [4]:
# Numpy Array
# kayak matriks ye


In [44]:
# Create Numpy Array

# 1. Bikin dari list
# 1 Dimensi
# list
nilai = [87, 90, 76, 100]

# subtitusi ke dalam fungsi py.array()
arr = py.array(nilai)

# print list
print(nilai)
print(type(nilai))

# print array
print(arr)
print(type(arr))

[87, 90, 76, 100]
<class 'list'>
[ 87  90  76 100]
<class 'numpy.ndarray'>


In [47]:
# 2 Dimensi
# list
nilai_2 = [[87, 90, 76, 100],[23,45,15,99]]

# subtitusi ke dalam fungsi py.array()
arr_2 = py.array(nilai_2)

# print list
print(nilai_2)
print(type(nilai_2))
print()

# print array
print(arr_2)
print(type(arr_2))
print()

[[87, 90, 76, 100], [23, 45, 15, 99]]
<class 'list'>

[[ 87  90  76 100]
 [ 23  45  15  99]]
<class 'numpy.ndarray'>



In [16]:
# 2. built in function di Numpy

# zeros
arr = py.zeros(10)
print(arr)
print(type(arr))
print()

# ones
arr = py.ones(13)
print(arr)
print(type(arr))
print()

# empty : kosong tapi ada isi, dianggap ga ada isinya
arr = py.empty(8)
print(arr)
print(type(arr))
print()

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
<class 'numpy.ndarray'>

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>

[0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000
 0.00000000e+000 7.64813620e-321 1.24610723e-306 1.29061142e-306]
<class 'numpy.ndarray'>



In [21]:
# arange batas atas dimulai dari 0
arr = py.arange(5)
print(arr)
print(type(arr))
print()

# arange batas atas dan bawah
arr = py.arange(3,18)
print(arr)
print(type(arr))
print()

# arange batas atas dan bawah dengan selisih
arr = py.arange(0,16,2)
print(arr)
print(type(arr))
print()

[0 1 2 3 4]
<class 'numpy.ndarray'>

[ 3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]
<class 'numpy.ndarray'>

[ 0  2  4  6  8 10 12 14]
<class 'numpy.ndarray'>



In [37]:
# random (jumlah bilangan)
arr = py.random.random(15)
print(arr)
print(type(arr))
print()

[0.57400052 0.55573609 0.23010044 0.48994824 0.5486738  0.76173181
 0.35459342 0.59223206 0.67151512 0.62041972 0.90794675 0.67571665
 0.45685006 0.01680228 0.67432753]
<class 'numpy.ndarray'>



In [40]:
# Numpy 2 dimensi
arr_2 = py.array([[7,3,4],[2,5,1]])
print(arr_2)

[[7 3 4]
 [2 5 1]]


In [29]:
# Read
# membaca array <name array.[index]

arr[1]


0.8759570375874175

In [41]:
print(arr.shape)
print(arr_2.shape)

(15,)
(2, 3)


In [42]:
print(arr.ndim)
print(arr_2.ndim)

1
2


In [43]:
print(arr.size)
print(arr_2.size)

15
6
